---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: notes-blahaj-cert
  namespace: joplin-server
spec:
  secretName: notes-blahaj-cert
  commonName: notes.blahaj.sh
  dnsNames:
    - notes.blahaj.sh
  issuerRef:
    name: blahaj-issuer
    kind: ClusterIssuer
    group: cert-manager.io
...
